# Generated by Django 5.0.6 on 2026-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_name', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Under Maintenance', 'Under Maintenance'), ('Unavailable', 'Unavailable')], default='Available', max_length=50)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laboratory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('campus', models.CharField(blank=True, default='', max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('lab_type', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Available', max_length=50)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'laboratories',
                'managed': False,
            },
        ),
    ]
