# Generated by Django 5.0.6 on 2026-03-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(max_length=255)),
                ('room', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Equipment', 'Equipment'), ('Facility', 'Facility'), ('Software', 'Software')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'issues',
                'ordering': ['-created_at'],
                'managed': False,
            },
        ),
    ]
